# Generated by Django 5.2 on 2025-06-09 07:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminanapp', '0002_alter_artwork_image_url_alter_gallery_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
