# Generated by Django 5.2 on 2025-06-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminanapp', '0004_saveartgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luminanapp.gallery'),
        ),
        migrations.AlterField(
            model_name='like',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luminanapp.artwork'),
        ),
        migrations.AlterField(
            model_name='saveartgallery',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luminanapp.artwork'),
        ),
        migrations.AlterField(
            model_name='saveartgallery',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luminanapp.gallery'),
        ),
    ]
