# Generated by Django 5.2 on 2025-06-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luminanapp', '0007_profile_facebook_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='ig',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='xtwt',
        ),
    ]
